import type { Metadata } from "next";
import { Montserrat, Inter } from "next/font/google";
import "./globals.css";

const monsterrat  = Montserrat({
  variable: "--font-montserrat",
  weight : ["500", "700"],
  subsets : ["latin"]
})

const inter  = Inter({
  variable: "--font-inter",
  weight : ["400","500", "700"],
  subsets : ["latin"]
})

export const metadata: Metadata = {
  title: "Sustyle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${monsterrat.className} ${inter.className} antialiased bg-gray-50 dark:bg-dark duration-200 dark:text-gray-100`}
      >
        {children}
      </body>
    </html>
  );
}
