import type { Metadata } from "next";
import { Ubuntu, Sora } from "next/font/google";
import "./globals.css";

const sora = Sora({
  weight : ["400", "500", "700"],
  subsets : ["latin"]
})

const ubuntu = Ubuntu({
  weight : ["400", "500", "700"],
  subsets : ["cyrillic-ext"]
})

export const metadata: Metadata = {
  title: "Wearth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ubuntu.className} antialiased bg-gray-50 dark:bg-dark duration-200 dark:text-gray-100`}
      >
        {children}
      </body>
    </html>
  );
}
